gui:
  showIcons: true
  nerdFontsVersion: "3"
  border: single
  theme:
    activeBorderColor:
      - blue
      - bold

git:
  paging:
    colorArg: always
    pager: delta --dark --side-by-side --paging=never
  autoFetch: true
